# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kidletime': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kwindowsystem': '@stable'

Options:
  require-passing-tests-on: [ '@all' ]
